use AIRLINE

SELECT * FROM VIEW_FLIGHT_PASENGER;

SELECT * FROM AGENCY;

INSERT INTO AGENCY_SOFIA 
VALUES('T1 Tour', 'Bulgaria', 'Sofia','+359');
INSERT INTO AGENCY_SOFIA_PH 
VALUES('T2 Tour', 'Bulgaria', 'Sofia',null);
INSERT INTO AGENCY_SOFIA 
VALUES('T3 Tour', 'Bulgaria', 'Varna','+359');
INSERT INTO AGENCY_SOFIA_PH 
VALUES('T4 Tour', 'Bulgaria', 'Varna',null);
INSERT INTO AGENCY_SOFIA_PH 
VALUES('T5 Tour', 'Bulgaria', 'Sofia','+359'); /*TASK6*/ SELECT * FROM  RICH_EXEC; SELECT * FROM MOVIEEXEC;  /*TASK7*/ SELECT * FROM EXCUTIVE_STAR; /*TASK9*/ SELECT NAME  FROM EXCUTIVE_STAR WHERE GENDER = 'F'; /*TASK10*/  SELECT RICH_EXEC.NAME  FROM EXCUTIVE_STAR,RICH_EXEC WHERE GENDER = 'M' AND EXCUTIVE_STAR.NAME = RICH_EXEC.NAME AND NETWORTH >= 50000000; /*TASK11*/ DROP VIEW VIEW_FLIGHT_PASENGER; DROP VIEW TOP_CUSTTOMERS; DROP VIEW AGENCY_SOFIA; DROP VIEW AGENCY_SOFIA_PH; DROP VIEW RICH_EXEC; DROP VIEW EXCUTIVE_STAR;