GO
USE FURNITURE_C
GO

SELECT PRODUCT.PRODUCT_ID, PRODUCT_DESCRIPTION,SUM(ORDRERED_QUANTITY) AS QUANTITY
FROM PRODUCT,ORDER_LINE
WHERE ORDER_LINE.PRODUCT_ID = PRODUCT.PRODUCT_ID
GROUP BY PRODUCT.PRODUCT_ID,PRODUCT_DESCRIPTION;

SELECT PRODUCT.PRODUCT_ID, PRODUCT_DESCRIPTION,ISNULL(SUM(ORDRERED_QUANTITY),0) AS QUANTITY
FROM PRODUCT
LEFT JOIN ORDER_LINE ON ORDER_LINE.PRODUCT_ID = PRODUCT.PRODUCT_ID
GROUP BY PRODUCT.PRODUCT_ID,PRODUCT_DESCRIPTION;

SELECT CUSTOMER.CUSTOMER_ID,SUM(PRODUCT.STANDARD_PRICE * ORDER_LINE.ORDRERED_QUANTITY)
FROM CUSTOMER,ORDER_T, ORDER_LINE,PRODUCT
WHERE CUSTOMER.CUSTOMER_ID = ORDER_T.CUSTOMER_ID
AND ORDER_T.ORDER_ID = ORDER_LINE.ORDER_ID
AND ORDER_LINE.PRODUCT_ID = PRODUCT.PRODUCT_ID
GROUP BY  CUSTOMER.CUSTOMER_ID
HAVING SUM(PRODUCT.STANDARD_PRICE * ORDER_LINE.ORDRERED_QUANTITY) > 0;