USE AIRLINE

ALTER TABLE FLIGHT
ADD NUM_PASS INT CONSTRAINT D_VALUE
    DEFAULT (0)
WITH VALUES;

ALTER TABLE FLIGHT
DROP COLUMN NUM_PASS;

ALTER TABLE AGENCY
ADD NUM_BOOK INT
CONSTRAINT D_VALUE_A
    DEFAULT (0)
WITH VALUES;

ALTER TABLE AGENCY
DROP COLUMN NUM_BOOK;
GO

/*TASK3*/
DROP TRIGGER IF EXISTS TRIGGER_INSERT_BOOKING
GO

CREATE TRIGGER TRIGGER_INSERT_BOOKING
ON BOOKING AFTER INSERT 
AS
BEGIN
	WITH FlightCounts AS (
    SELECT FLIGHT_NUMBER, COUNT(*) AS BookingCount
    FROM inserted
    GROUP BY FLIGHT_NUMBER
    )

	UPDATE FLIGHT 
    SET NUM_PASS = NUM_PASS + BookingCount
    FROM FLIGHT ,FlightCounts
    WHERE FNUMBER = FLIGHT_NUMBER;

	WITH AgencyCounts AS (
    SELECT AGENCY, COUNT(*) AS BookingCount
    FROM inserted
    GROUP BY AGENCY
    )

    UPDATE AGENCY 
    SET NUM_BOOK = NUM_BOOK +BookingCount
    FROM AGENCY,AgencyCounts
    WHERE NAME = AGENCY;
END;


SELECT * 
FROM BOOKING;

SELECT * 
FROM AGENCY;

SELECT * 
FROM FLIGHT;
GO

/*TASK4*/
CREATE TRIGGER TRIGGER_DELETE_BOOKING
ON BOOKING AFTER DELETE 
AS
BEGIN
	WITH FlightCounts AS (
    SELECT FLIGHT_NUMBER, COUNT(*) AS BookingCount
    FROM deleted
    GROUP BY FLIGHT_NUMBER
    )

	UPDATE FLIGHT 
    SET NUM_PASS = NUM_PASS - BookingCount
    FROM FLIGHT ,FlightCounts
    WHERE FNUMBER = FLIGHT_NUMBER;

	WITH AgencyCounts AS (
    SELECT AGENCY, COUNT(*) AS BookingCount
    FROM deleted
    GROUP BY AGENCY
    )

    UPDATE AGENCY 
    SET NUM_BOOK = NUM_BOOK - BookingCount
    FROM AGENCY,AgencyCounts
    WHERE NAME = AGENCY;
END;

DELETE FROM BOOKING WHERE CODE='YN298P';
GO
/*TASK5*/

CREATE TRIGGER UpdateBookingStatus
ON BOOKING
AFTER UPDATE
AS
IF ( UPDATE (STATUS))
BEGIN
	UPDATE FLIGHT 
    SET NUM_PASS +=1 
    FROM FLIGHT ,deleted,inserted
    WHERE FNUMBER = deleted.FLIGHT_NUMBER
	AND FNUMBER = inserted.FLIGHT_NUMBER
	AND deleted.STATUS < inserted.STATUS

	UPDATE FLIGHT 
    SET NUM_PASS -=1 
    FROM FLIGHT ,deleted,inserted
    WHERE FNUMBER = deleted.FLIGHT_NUMBER
	AND FNUMBER = inserted.FLIGHT_NUMBER
	AND deleted.STATUS > inserted.STATUS
END;

UPDATE BOOKING
SET STATUS = 0
WHERE CODE = 'YA298P';

SELECT * 
FROM BOOKING;

SELECT * 
FROM FLIGHT;