CREATE VIEW VIEW_FLIGHT_PASENGER AS
SELECT AIRLINE.NAME AS AIRLINE,BOOKING.FLIGHT_NUMBER,COUNT(BOOKING.CUSTOMER_ID) AS PASENDERS
FROM FLIGHT,AIRLINE,BOOKING
WHERE FLIGHT.AIRLINE_OPERATOR = AIRLINE.CODE
AND FLIGHT.FNUMBER = BOOKING.FLIGHT_NUMBER
AND BOOKING.STATUS = 1
GROUP BY AIRLINE.NAME, BOOKING.FLIGHT_NUMBER;
