CREATE VIEW TOP_CUSTTOMERS AS
SELECT COUNTS.AGENCY,CUSTOMER.FNAME,CUSTOMER.LNAME
FROM (SELECT AGENCY, CUSTOMER_ID, COUNT(*) AS BOOKING_COUNT
	  FROM 
      BOOKING
	  GROUP BY AGENCY, CUSTOMER_ID) COUNTS
	  ,CUSTOMER 
	  ,(SELECT AGENCY,MAX(BOOKING_COUNT) AS BOOKING_COUNT_MAX
		FROM (SELECT AGENCY, CUSTOMER_ID, COUNT(*) AS BOOKING_COUNT
			  FROM BOOKING
			  GROUP BY AGENCY, CUSTOMER_ID) COUNTS
		GROUP BY AGENCY) AS COUNTS_MAX

WHERE COUNTS.CUSTOMER_ID = CUSTOMER.ID
AND   COUNTS_MAX.AGENCY = COUNTS.AGENCY
AND   COUNTS.BOOKING_COUNT = COUNTS_MAX.BOOKING_COUNT_MAX;

