CREATE DATABASE AIRLINE
GO
USE AIRLINE
GO

CREATE TABLE AIRLINE (
 CODE INT NOT NULL,
 NAME CHAR(50) NOT NULL UNIQUE,
 COUNTRY VARCHAR (20) NOT NULL
);

CREATE TABLE AIRPLANE (
 CODE INT NOT NULL,
 TYPE CHAR(10) NOT NULL,
 SEATS INT  CHECK (SEATS <= 0) NOT NULL,
 YEAR INT
);

CREATE TABLE AGENCY (
 NAME CHAR(50) NOT NULL UNIQUE,
 COUNTRY VARCHAR (20) NOT NULL,
 CITY VARCHAR (20) NOT NULL,
 PHONE VARCHAR(10) NOT NULL
);

CREATE TABLE CUSTOMER(
 ID INT NOT NULL,
 FNAME CHAR(50) NOT NULL,
 LNAME CHAR(50) NOT NULL,
 EMAIL CHAR(50) CHECK ((LEN(EMAIL) >= 6) AND (EMAIL LIKE '_%@_%._%')) NOT NULL 
);

CREATE TABLE AIRPORT(
 CODE INT NOT NULL,
 NAME CHAR(50) NOT NULL UNIQUE,
 COUNTRY VARCHAR (20) NOT NULL,
 CITY VARCHAR (20) NOT NULL,
);

CREATE TABLE BOOKING(
 CODE INT NOT NULL,
 AGENCY CHAR(50) NOT NULL,
 AIRLINE_CODE  INT NOT NULL,
 FLIGHT_NUMBER INT NOT NULL,
 CUSTOMER_ID INT NOT NULL,
 BOOKING_DATE DATETIME NOT NULL,
 FLIGHT_DATE DATETIME NOT NULL,
 PRICE DECIMAL(10, 2) NOT NULL,
 STATUS INT DEFAULT 0 CHECK (STATUS IN (0, 1)) NOT NULL,
 CONSTRAINT CHEK_DATE CHECK (FLIGHT_DATE >= BOOKING_DATE),
 CONSTRAINT CHEK_STATUS CHECK (STATUS IN (0, 1))
);

CREATE TABLE FLIGHT(
 FNUMBER INT NOT NULL,
 AIRLINE_OPERATOR  INT NOT NULL,
 DEP_AIRPORT INT NOT NULL,
 ARR_AIRPORT INT NOT NULL,
 FLIGHT_TIME DATETIME NOT NULL,
 FLIGHT_DURATION INT NOT NULL,
 AIRPLANE INT NOT NULL
);

ALTER TABLE AIRLINE ADD CONSTRAINT PK_AIRLINE PRIMARY KEY (CODE);

ALTER TABLE AIRPLANE ADD CONSTRAINT PK_AIRPLANE PRIMARY KEY (CODE);

ALTER TABLE AGENCY ADD CONSTRAINT PK_AGENCY PRIMARY KEY (NAME,COUNTRY);

ALTER TABLE CUSTOMER ADD CONSTRAINT PK_CUSTOMER PRIMARY KEY (ID);

ALTER TABLE AIRPORT ADD CONSTRAINT PK_AIRPORT PRIMARY KEY (CODE);

ALTER TABLE BOOKING ADD CONSTRAINT PK_BOOKING PRIMARY KEY (CODE);

ALTER TABLE FLIGHT ADD CONSTRAINT PK_FLIGHT PRIMARY KEY (FNUMBER);

ALTER TABLE FLIGHT ADD CONSTRAINT FK_FLIGHT_AIRLINE FOREIGN KEY(AIRLINE_OPERATOR) REFERENCES AIRLINE(CODE);

ALTER TABLE BOOKING ADD CONSTRAINT FK_BOOKING_AIRLINE FOREIGN KEY(AIRLINE_CODE) REFERENCES AIRLINE(CODE);

ALTER TABLE FLIGHT ADD CONSTRAINT FK_DEP_AIRPORT FOREIGN KEY(DEP_AIRPORT) REFERENCES AIRPORT(CODE);

ALTER TABLE FLIGHT ADD CONSTRAINT FK_ARR_AIRPORT FOREIGN KEY(ARR_AIRPORT) REFERENCES AIRPORT(CODE);

ALTER TABLE FLIGHT ADD CONSTRAINT FK_FLIGHT_AIRPLANE FOREIGN KEY(AIRPLANE) REFERENCES AIRPLANE(CODE);

ALTER TABLE BOOKING ADD CONSTRAINT FK_BOOKING_AGENCY FOREIGN KEY(AGENCY) REFERENCES AGENCY(NAME);

ALTER TABLE BOOKING ADD CONSTRAINT FK_FLIGHT_BOOKING FOREIGN KEY(FLIGHT_NUMBER) REFERENCES FLIGHT(FNUMBER);

ALTER TABLE BOOKING ADD CONSTRAINT FK_CUSTOMER_BOOKING FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(ID);