use ships;
CREATE INDEX INGEX_CLASSES_TYPE ON CLASSES(TYPE);
CREATE INDEX INGEX_CLASSES_COUNTRY_CLAS ON CLASSES(CLASS,COUNTRY);

CREATE INDEX INGEX_SHIPS_CLASS ON SHIPS(CLASS);

CREATE INDEX INGEX_BATTLES_DATE ON BATTLES(DATE);

CREATE INDEX INGEX_OUTKOMES_BATTLE_RESULT ON OUTCOMES(BATTLE,RESULT);

drop index CLASSES.INGEX_CLASSES_TYPE;
drop index CLASSES.INGEX_CLASSES_COUNTRY_CLAS;
drop index SHIPS.INGEX_SHIPS_CLASS;
drop index BATTLES.INGEX_BATTLES_DATE;
drop index OUTCOMES.INGEX_OUTKOMES_BATTLE_RESULT;
