use ships_without_constraints

/*TASK1*/
SELECT *
FROM CLASSES

SELECT *
FROM SHIPS

INSERT INTO CLASSES
  VALUES ('Nelson', 'bb', 'Gt.Britain', 9, 16, 34000);

INSERT INTO SHIPS
  VALUES ('Nelson', 'Nelson', 1927);
INSERT INTO SHIPS
  VALUES ('Rodney', 'Nelson', 1927);

/*TASK2*/
SELECT *
FROM SHIPS

DELETE FROM SHIPS
WHERE NAME IN (SELECT NAME
			 FROM SHIPS,OUTCOMES 
			 WHERE SHIPS.NAME = OUTCOMES.SHIP
			AND OUTCOMES.RESULT = 'sunk');

/*TASK5*/
SELECT *
FROM CLASSES

UPDATE CLASSES
SET BORE *= 2.5, DISPLACEMENT *=  1.1;