use ships
GO 

CREATE VIEW MORE_SHIPS AS
SELECT BATTLE
FROM OUTCOMES
GROUP BY BATTLE
HAVING COUNT(*) > (SELECT COUNT(*)
					FROM OUTCOMES
					WHERE BATTLE = 'Guadalcanal'
					GROUP BY BATTLE);

GO
CREATE VIEW MORE_COUNTRYES AS
SELECT BATTLE
FROM OUTCOMES,CLASSES ,SHIPS
WHERE SHIPS.CLASS = CLASSES.CLASS 
AND SHIPS.NAME = OUTCOMES.SHIP
GROUP BY BATTLE
HAVING COUNT(DISTINCT COUNTRY) > (SELECT COUNT(DISTINCT COUNTRY)
								  FROM OUTCOMES,CLASSES ,SHIPS
								  WHERE SHIPS.CLASS = CLASSES.CLASS 
								  AND SHIPS.NAME = OUTCOMES.SHIP
								  AND BATTLE = ' Guadalcanal'
					GROUP BY BATTLE);
GO
SELECT * FROM MORE_COUNTRYES;