use ships

SELECT *
FROM OUTCOMES;

SELECT *
FROM BATTLES;

SELECT *
FROM CLASSES;

/*TASK1*/
SELECT DISTINCT NAME
FROM SHIPS, OUTCOMES
WHERE SHIPS.NAME IN (OUTCOMES.SHIP)
AND (NAME LIKE 'C%'
OR NAME LIKE 'K%');

/*TASK2*/
SELECT NAME, COUNTRY
FROM SHIPS ,CLASSES 
WHERE SHIPS.CLASS = CLASSES.CLASS
AND SHIPS.NAME NOT IN (
    SELECT SHIP
    FROM OUTCOMES
    WHERE RESULT = 'sunk'
);

/*TASK3*/
SELECT COUNTRY,COUNT(CASE WHEN RESULT = 'sunk' THEN 1 ELSE NULL END)
FROM CLASSES ,SHIPS
LEFT JOIN OUTCOMES ON SHIPS.NAME = OUTCOMES.SHIP
WHERE SHIPS.CLASS = CLASSES.CLASS 
AND RESULT = 'sunk' 
OR RESULT IS NULL
GROUP BY COUNTRY

/*TASK4*/
SELECT BATTLE,COUNT(*)
FROM OUTCOMES
GROUP BY BATTLE
HAVING COUNT(*) > (SELECT COUNT(*)
					FROM OUTCOMES
					WHERE BATTLE = 'Guadalcanal'
					GROUP BY BATTLE);

/*TASK5*/
SELECT BATTLE
FROM OUTCOMES,CLASSES ,SHIPS
WHERE SHIPS.CLASS = CLASSES.CLASS 
AND SHIPS.NAME = OUTCOMES.SHIP
GROUP BY BATTLE
HAVING COUNT(DISTINCT COUNTRY) > (SELECT COUNT(DISTINCT COUNTRY)
					FROM OUTCOMES,CLASSES ,SHIPS
					WHERE SHIPS.CLASS = CLASSES.CLASS 
					AND SHIPS.NAME = OUTCOMES.SHIP
					AND BATTLE = 'Surigao Strait'
					GROUP BY BATTLE);

/*TASK6*/
SELECT NAME, DISPLACEMENT, NUMGUNS
FROM CLASSES ,SHIPS
WHERE CLASSES.CLASS = SHIPS.CLASS
AND DISPLACEMENT = (
    SELECT MIN(DISPLACEMENT) 
    FROM CLASSES 
    WHERE NUMGUNS = (
        SELECT MAX(NUMGUNS)
        FROM CLASSES
        WHERE DISPLACEMENT = (SELECT MIN(DISPLACEMENT) FROM CLASSES)
    )
);

/*TASK7*/
SELECT O1.SHIP
FROM OUTCOMES O1
JOIN OUTCOMES O2 ON O1.SHIP = O2.SHIP
JOIN BATTLES B1 ON O1.BATTLE = B1.NAME
JOIN BATTLES B2 ON O2.BATTLE = B2.NAME
WHERE O1.RESULT = 'damaged' 
AND B1.DATE < B2.DATE
AND O2.RESULT = 'ok';

/*TASK8*/
SELECT O1.SHIP
FROM OUTCOMES O1
JOIN OUTCOMES O2 ON O1.SHIP = O2.SHIP
JOIN BATTLES B1 ON O1.BATTLE = B1.NAME
JOIN BATTLES B2 ON O2.BATTLE = B2.NAME
WHERE O1.RESULT = 'damaged'
AND B1.DATE < B2.DATE
AND O2.RESULT = 'ok'
AND (SELECT COUNT(SHIP) 
	FROM OUTCOMES 
	WHERE BATTLE = B1.NAME)
	< 
	(SELECT COUNT(SHIP) 
	FROM OUTCOMES 
	WHERE BATTLE = B2.NAME);
