use movies

SELECT *
FROM STARSIN;

/*TASK1*/
SELECT TITLE,YEAR,LENGTH
FROM MOVIE
WHERE (LENGTH > 120
OR LENGTH IS NULL)
AND (YEAR < 2000
OR YEAR IS NULL);

/*TASK2*/
SELECT NAME,GENDER
FROM MOVIESTAR
WHERE NAME LIKE 'J%'
AND BIRTHDATE > 1948
ORDER BY NAME DESC;

/*TASK3*/
SELECT STUDIO.NAME,COUNT(NAME) AS NUM_ACTORS
FROM STUDIO,MOVIE,STARSIN
WHERE STUDIO.NAME=MOVIE.STUDIONAME
AND MOVIE.TITLE=STARSIN.MOVIETITLE
AND MOVIE.YEAR=STARSIN.MOVIEYEAR
GROUP BY STUDIO.NAME;

/*TASK4*/
SELECT MOVIESTAR.NAME,COUNT(MOVIETITLE) AS NUM_MOVIES
FROM MOVIESTAR,STARSIN
WHERE STARSIN.STARNAME = MOVIESTAR.NAME
GROUP BY NAME;

/*TASK5*/
SELECT MOVIE.STUDIONAME, TITLE,MOVIE.YEAR
FROM MOVIE
INNER JOIN (SELECT STUDIONAME, MAX(YEAR) AS MAXYEAR
			FROM MOVIE
			GROUP BY STUDIONAME) AS MOVIE_MAX 
ON MOVIE.STUDIONAME = MOVIE_MAX.STUDIONAME AND YEAR = MOVIE_MAX.MAXYEAR
ORDER BY MOVIE.STUDIONAME DESC;

/*TASK6*/
SELECT NAME
FROM MOVIESTAR
INNER JOIN (SELECT GENDER, MAX(BIRTHDATE) AS MAX
			FROM MOVIESTAR
			GROUP BY GENDER
			HAVING GENDER = 'M') AS MIN_GENDER 
ON MOVIESTAR.GENDER = MIN_GENDER.GENDER AND MOVIESTAR.BIRTHDATE = MIN_GENDER.MAX;

/*TASK7*/
SELECT ALL_VALUES.STUDIONAME, ALL_VALUES.STARNAME, ALL_VALUES.COUNT
FROM (SELECT STUDIONAME,STARNAME,COUNT(STARNAME)AS COUNT
	  FROM  MOVIE,STARSIN
	  WHERE MOVIETITLE = TITLE
	  AND MOVIEYEAR = YEAR
	  GROUP BY STUDIONAME, STARNAME) AS ALL_VALUES,

	 (SELECT STUDIONAME,MAX(COUNT) AS MAX
      FROM (SELECT STUDIONAME,STARNAME,COUNT(STARNAME)AS COUNT
		    FROM  MOVIE,STARSIN
		    WHERE MOVIETITLE = TITLE
		    AND MOVIEYEAR = YEAR
		    GROUP BY STUDIONAME, STARNAME)AS COUNTS
    GROUP BY STUDIONAME)AS MAX_VALUES

WHERE ALL_VALUES.STUDIONAME = MAX_VALUES.STUDIONAME AND ALL_VALUES.COUNT = MAX_VALUES.MAX;

/*TASK8*/
SELECT MOVIETITLE,MOVIEYEAR,COUNT(STARNAME)AS COUNT
FROM  MOVIE,STARSIN
WHERE MOVIETITLE = TITLE
AND MOVIEYEAR = YEAR
GROUP BY MOVIETITLE, MOVIEYEAR
HAVING COUNT(STARNAME) > 2 