use movies

SELECT *
FROM STARSIN;

SELECT *
FROM MOVIE;

SELECT *
FROM STUDIO;

/*TASK1*/
SELECT TITLE,YEAR,LENGTH
FROM MOVIE
WHERE (LENGTH > 120
OR LENGTH IS NULL)
AND (YEAR < 2000
OR YEAR IS NULL);

/*TASK2*/
SELECT NAME,GENDER
FROM MOVIESTAR
WHERE NAME LIKE 'J%'
AND BIRTHDATE > 1948
ORDER BY NAME DESC;

/*TASK3*/
SELECT STUDIO.NAME,COUNT(NAME) AS NUM_ACTORS
FROM STUDIO,MOVIE,STARSIN
WHERE STUDIO.NAME=MOVIE.STUDIONAME
AND MOVIE.TITLE=STARSIN.MOVIETITLE
AND MOVIE.YEAR=STARSIN.MOVIEYEAR
GROUP BY STUDIO.NAME;

/*TASK4*/
SELECT MOVIESTAR.NAME,COUNT(MOVIETITLE) AS NUM_MOVIES
FROM MOVIESTAR,STARSIN
WHERE STARSIN.STARNAME = MOVIESTAR.NAME
GROUP BY NAME;