use movies

SELECT *
FROM MOVIEEXEC;

SELECT *
FROM MOVIESTAR;


INSERT INTO MOVIEEXEC
  VALUES (198, 'Sandra Bullock', 'X path', 55000000);

INSERT INTO MOVIEEXEC
  VALUES (150, 'Jack Nicholson', 'X path', 50000000);


SELECT NAME
FROM MOVIESTAR
WHERE  GENDER = 'F'
AND NAME IN (SELECT NAME
				FROM MOVIEEXEC
				WHERE  NETWORTH > 10000000);

SELECT NAME
FROM MOVIESTAR
WHERE NAME NOT IN (SELECT NAME
				FROM MOVIEEXEC);

SELECT TITLE
FROM MOVIE
WHERE LENGTH > (SELECT LENGTH
				FROM MOVIE
				WHERE TITLE = 'Star Wars');

SELECT TITLE,MOVIEEXEC.NAME
FROM MOVIE, MOVIEEXEC
WHERE MOVIE.PRODUCERC# = MOVIEEXEC.CERT#
AND NETWORTH > (SELECT NETWORTH
				FROM MOVIEEXEC
				WHERE NAME = 'Merv Griffin');