use ships

SELECT *
FROM CLASSES;

 /*task1*/
SELECT COUNT(CLASS) AS CLASSES
FROM CLASSES;

 /*task2*/
SELECT CLASS, AVG(NUMGUNS) AS AVG
FROM CLASSES
GROUP BY CLASS;

 /*task3*/
SELECT AVG(NUMGUNS) AS AVG
FROM CLASSES;

 /*task4*/
SELECT CLASS,MIN(LAUNCHED) AS FIRST,MAX(LAUNCHED) AS LAST
FROM SHIPS
GROUP BY CLASS;
 
 /*task5*/
SELECT CLASS, COUNT(CLASS) AS SUNK
FROM SHIPS, OUTCOMES
WHERE SHIPS.NAME = OUTCOMES.SHIP
AND RESULT = 'sunk'
GROUP BY CLASS;


 /*task6*/
SELECT CLASS, COUNT(CLASS) AS SUNK
FROM SHIPS, OUTCOMES
WHERE SHIPS.NAME = OUTCOMES.SHIP
AND RESULT = 'sunk'
GROUP BY CLASS
HAVING COUNT(CLASS)>1;

 /*task7*/
SELECT COUNTRY, CAST(AVG(BORE) AS DECIMAL(10,2))as AVG
FROM CLASSES
GROUP BY COUNTRY;