use movies

SELECT *
FROM MOVIEEXEC;

SELECT NAME
FROM MOVIESTAR, STARSIN
WHERE STARSIN.STARNAME = MOVIESTAR.NAME
AND MOVIETITLE = 'The Usual Suspects'
AND GENDER = 'M';

SELECT STARNAME AS NAME
FROM MOVIE, STARSIN
WHERE STARSIN.MOVIETITLE = MOVIE.TITLE
AND STARSIN.MOVIEYEAR = MOVIE.YEAR
AND YEAR = 1995
AND STUDIONAME = 'MGM';

SELECT DISTINCT NAME
FROM MOVIE, MOVIEEXEC
WHERE MOVIEEXEC.CERT# = MOVIE.PRODUCERC#
AND STUDIONAME = 'MGM';

SELECT M1.TITLE AS TITLE
FROM MOVIE AS M1,MOVIE AS M2
WHERE M2.TITLE = 'Star Wars'
AND M1.LENGTH > M2.LENGTH;

SELECT P1.NAME AS NAME
FROM MOVIEEXEC AS P1,MOVIEEXEC AS P2
WHERE P2.NAME = 'Stephen Spielberg'
AND P1.NETWORTH > P2.NETWORTH;

SELECT P1.NAME AS NAME, TITLE
FROM MOVIEEXEC AS P1,MOVIEEXEC AS P2, MOVIE
WHERE MOVIE.PRODUCERC# = P1.CERT#
AND P2.NAME = 'Stephen Spielberg'
AND P1.NETWORTH > P2.NETWORTH
ORDER BY P1.NAME;