use movies

SELECT *
FROM MOVIESTAR;

SELECT *
FROM STUDIO
WHERE NAME = 'Disney';

SELECT FORMAT (BIRTHDATE, 'dd-MM-yyyy') as BIRTHDATE
FROM MOVIESTAR
WHERE NAME = 'Jack Nicholson';

INSERT INTO MOVIE
  VALUES ('Knight and Dragons', 1985, 124, 'Y', 'Fox', 555);

INSERT INTO STARSIN
  VALUES ('Knight and Dragons', 1985, 'Kim Basinger');

SELECT STARNAME AS NAME
FROM STARSIN
WHERE MOVIEYEAR = 1980
OR MOVIETITLE  LIKE '%Knight%';

SELECT NAME, CERT#
FROM MOVIEEXEC
WHERE NETWORTH > 100000000;

SELECT NAME
FROM MOVIESTAR
WHERE GENDER = 'M'
OR ADDRESS = 'Prefect Rd';
